name: Acquire activation file
on:
  workflow_dispatch:{}
jobs:
  activation:
    name: Request Manual activation file
    runs-on: ubuntu-latest
    steps:
      #Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
      #Upload artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{steps.getManualLicenseFile.output.filepath}}
          path: ${{steps.getManualLicenseFile.output.filepath}}